medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: "1234"  
      port: 5432
      dbname: medical_warehouse
      schema: public
      threads: 1