version: 2

sources:
  - name: raw
    description: "Raw data loaded from Telegram JSONs"
    database: medical_warehouse
    schema: raw
    tables:
      - name: telegram_messages
        description: "Raw messages scraped from Telegram channels"
      
      - name: image_detections
        description: "Objects detected in images using YOLOv8"